---
- name: named.conf.local
  template:
    src: templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: bind_restart

- name: name.conf.options
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: bind_restart

- name: zone file directory
  file:
    state: directory
    path: /var/lib/bind
    owner: bind
    group: bind
