- name: Install bind9 server 
  apt: 
    name: bind9
    state: present 
    update_cache: yes

# -- Render config templates into /etc/bind9
- name: Configure server 
  include_tasks: config.yml

# -- Generate the zone files:
- name: Configure bind9 zone files
  include_tasks: zone.yml
  loop: "{{ zones }}"
  loop_control: 
    loop_var: zone


